 version: '2'
 services:
   db:
     image: mdillon/postgis
     environment: 
      POSTGRES_USER: cruzroja
      POSTGRES_PASSWORD: cruzroja
      POSTGRES_DB: cruzroja
   web:
     build: .
     command: bash -c "sleep 8 && python manage.py runserver 0.0.0.0:8000"
     volumes:
       - .:/code
     ports:
       - "8000:8000"
     depends_on:
       - db

